name: Render Quarto Report

on:
  schedule:
    - cron: "0 12 * * *"   # roda todo dia às 12:00 UTC (9h no Brasil)
  workflow_dispatch:        # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Render Quarto report
      run: quarto render "Projeto IPCA Conjuntura.qmd" --to html


    - name: Publish to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
