name: Render Quarto Report

on:
  schedule:
    - cron: "0 11 * * *"   # roda todo dia às 12:00 UTC (8h no Brasil)
  workflow_dispatch:        # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies (no cache)
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Render Quarto report
      run: quarto render "Projeto IPCA Conjuntura.qmd" --to html


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
