name: Test Secret

on: [workflow_dispatch]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret exists
        run: |
          if [ -z "${{ secrets.QUARTO_PUB_AUTH_TOKEN }}" ]; then
            echo "Token is empty"
            exit 1
          else
            echo "Token is set"
          fi
