name: Render and Publish Quarto site

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Caso tenha script Python separado para gerar dados/textos, execute aqui
    # - name: Run Python script
    #   run: python seu_script.py

    - name: Install Quarto CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg curl software-properties-common
        curl -fsSL https://quarto.org/keys/public.asc | sudo tee /etc/apt/trusted.gpg.d/quarto.asc
        sudo add-apt-repository "deb https://quarto.org/download/linux/ focal main"
        sudo apt-get update
        sudo apt-get install -y quarto


    - name: Render Quarto file
      run: quarto render "Projeto IPCA Conjuntura.qmd"

    - name: Publish site to GitHub Pages
      run: quarto publish github --project . --branch gh-pages --no-push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push gh-pages branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout gh-pages
        git add .
        git commit -m "Publicar site Quarto atualizado"
        git push origin gh-pages
